[tox]
envlist = pytest, code-cov, flake8, sphinx

[gh-actions]
python =
    3.6: pytest
    3.7: pytest
    3.8: pytest
    3.9: pytest
    3.10: pytest, flake8, sphinx

[flake8]
max-line-length = 120

[coverage:report]
exclude_lines =
    # Have to re-enable the standard pragma
    pragma: no cover

    # Don't complain if tests don't hit defensive assertion code:
    pass
omit =
    */__init__.py



[testenv:pytest]
deps =
    pyfakefs
    pytest
commands =
    pytest

[testenv:coverage]
deps =
    pyfakefs
    pytest
    pytest-cov
commands =
    pytest --cov-report xml --cov=gcsa tests

[testenv:flake8]
deps =
    flake8
commands =
    flake8 gcsa tests setup.py

[testenv:sphinx]
deps =
    sphinx
    sphinx_rtd_theme
commands =
    sphinx-build -W docs/source docs/build
